# Generated by Django 5.2.3 on 2025-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_user_settings_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for the account setup', max_length=254)),
                ('first_name', models.CharField(help_text='First name from batch import', max_length=50)),
                ('last_name', models.CharField(help_text='Last name from batch import', max_length=50)),
                ('token', models.CharField(help_text='Unique token for account setup', max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this token has been used')),
                ('expires_at', models.DateTimeField(help_text='When this token expires')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was created')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was used', null=True)),
            ],
            options={
                'verbose_name': 'Account Setup Token',
                'verbose_name_plural': 'Account Setup Tokens',
                'db_table': 'account_setup_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_language_pref_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_theme_pref_idx',
        ),
        migrations.AddIndex(
            model_name='accountsetuptoken',
            index=models.Index(fields=['token'], name='account_set_token_36ed76_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsetuptoken',
            index=models.Index(fields=['email'], name='account_set_email_948045_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsetuptoken',
            index=models.Index(fields=['expires_at'], name='account_set_expires_f2a6dc_idx'),
        ),
    ]
