# Generated by Django 5.2.3 on 2025-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accountsetuptoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetuptoken',
            name='tutor_id',
            field=models.CharField(blank=True, help_text='Tutor ID from batch import', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='accountsetuptoken',
            index=models.Index(fields=['tutor_id'], name='account_set_tutor_i_2d1faa_idx'),
        ),
    ]
