# Generated by Django 5.2.3 on 2025-06-30 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Tutor's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Tutor's last name", max_length=50)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_address', models.EmailField(help_text='Email address for communication', max_length=254, unique=True)),
                ('physical_address', models.TextField(help_text='Complete physical address', max_length=300)),
                ('highest_qualification', models.CharField(choices=[('high_school', 'High School Diploma'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('other', 'Other')], default='bachelors', help_text='Highest educational qualification achieved', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this tutor is currently active')),
                ('is_blocked', models.BooleanField(default=False, help_text='Designates whether this tutor is blocked from the system')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the tutor was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the tutor was last updated')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutors',
                'db_table': 'tutors',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email_address'], name='tutors_email_a_248843_idx'), models.Index(fields=['phone_number'], name='tutors_phone_n_5d0faf_idx'), models.Index(fields=['is_active', 'is_blocked'], name='tutors_is_acti_ccb0a2_idx')],
            },
        ),
    ]
