# Generated by Django 5.2.3 on 2025-07-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tutor_id',
            field=models.CharField(blank=True, help_text='Custom tutor ID (e.g., TUT-0001). Leave blank to auto-generate.', max_length=20, null=True, unique=True),
        ),
    ]
