# Generated by Django 5.2.3 on 2025-06-30 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
        ('tutors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gigsession',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this session has been verified by an administrator'),
        ),
        migrations.AddField(
            model_name='gigsession',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When this session was verified', null=True),
        ),
        migrations.AddField(
            model_name='gigsession',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who verified this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='Assigned tutor for this gig', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='tutors.tutor'),
        ),
        migrations.AddIndex(
            model_name='gigsession',
            index=models.Index(fields=['gig', 'session_date'], name='gig_session_gig_id_831db7_idx'),
        ),
        migrations.AddIndex(
            model_name='gigsession',
            index=models.Index(fields=['is_verified'], name='gig_session_is_veri_441a13_idx'),
        ),
    ]
