# Generated by Django 5.2.3 on 2025-10-19 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gigsession_is_verified_gigsession_verified_at_and_more'),
        ('tutors', '0002_tutor_tutor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_code', models.CharField(db_index=True, help_text='Unique code for accessing the meeting', max_length=12, unique=True)),
                ('pin_code', models.CharField(help_text='6-digit PIN for additional security', max_length=6)),
                ('room_name', models.CharField(help_text='Jitsi room name/ID', max_length=255)),
                ('scheduled_start', models.DateTimeField(help_text='Scheduled start time of the session')),
                ('scheduled_end', models.DateTimeField(help_text='Scheduled end time of the session')),
                ('actual_start', models.DateTimeField(blank=True, help_text='Actual start time (when first participant joins)', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='Actual end time (when session is manually ended or auto-completed)', null=True)),
                ('extended_end', models.DateTimeField(blank=True, help_text='Extended end time if session was extended', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the online session', max_length=20)),
                ('session_notes', models.TextField(blank=True, help_text='Notes about the session')),
                ('tutor_joined', models.BooleanField(default=False, help_text='Whether tutor has joined the session')),
                ('client_joined', models.BooleanField(default=False, help_text='Whether client has joined the session')),
                ('tutor_joined_at', models.DateTimeField(blank=True, help_text='When tutor joined', null=True)),
                ('client_joined_at', models.DateTimeField(blank=True, help_text='When client joined', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_online_sessions', to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(help_text='Associated gig', on_delete=django.db.models.deletion.CASCADE, related_name='online_sessions', to='gigs.gig')),
                ('tutor', models.ForeignKey(help_text='Tutor conducting the session', on_delete=django.db.models.deletion.CASCADE, related_name='online_sessions', to='tutors.tutor')),
            ],
            options={
                'verbose_name': 'Online Session',
                'verbose_name_plural': 'Online Sessions',
                'db_table': 'online_sessions',
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['meeting_code'], name='online_sess_meeting_9cff94_idx'), models.Index(fields=['status', 'scheduled_start'], name='online_sess_status_75209d_idx'), models.Index(fields=['gig', 'scheduled_start'], name='online_sess_gig_id_316a75_idx')],
            },
        ),
    ]
