# Generated by Django 5.2.3 on 2025-10-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_add_online_session_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinesession',
            name='meeting_code',
            field=models.CharField(db_index=True, help_text='Unique code for accessing the meeting', max_length=15, unique=True),
        ),
    ]
