# Generated by Django 5.2.3 on 2025-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_fix_meeting_code_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinesession',
            name='digital_samba_room_id',
            field=models.CharField(blank=True, help_text='Digital Samba room ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlinesession',
            name='digital_samba_room_url',
            field=models.URLField(blank=True, help_text='Digital Samba room URL', null=True),
        ),
        migrations.AlterField(
            model_name='onlinesession',
            name='room_name',
            field=models.CharField(help_text='Digital Samba room name/ID', max_length=255),
        ),
    ]
