# Generated by Django 5.2.3 on 2025-10-19 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_onlinesession_digital_samba_room_id_and_more'),
        ('tutors', '0002_tutor_tutor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start', models.DateTimeField(help_text='Requested start date and time for the session')),
                ('requested_duration', models.IntegerField(default=60, help_text='Requested duration in minutes (15-300)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(300)])),
                ('request_notes', models.TextField(blank=True, help_text='Additional notes from the tutor about the session')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin about the decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_session', models.OneToOneField(blank=True, help_text='The online session created from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='gigs.onlinesession')),
                ('gig', models.ForeignKey(help_text='The gig this meeting request is for', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='gigs.gig')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meeting_requests', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(help_text='The tutor making the request', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='tutors.tutor')),
            ],
            options={
                'verbose_name': 'Online Meeting Request',
                'verbose_name_plural': 'Online Meeting Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
